name: CI Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'
          cache-disabled: true
          generate-job-summary: false

      - name: Build Debug & Release
        run: gradle assembleDebug assembleRelease --no-daemon
